"use client";
import {useEffect,useState} from "react";
type A={id:string;email:string;name:string;role:string};
export default function Admins(){const [items,setItems]=useState<A[]>([]);const [email,setEmail]=useState("");const [name,setName]=useState("");const [password,setPassword]=useState("");const [msg,setMsg]=useState("");
async function load(){const r=await fetch("/api/admin/admins");if(r.status===401){location.href="/admin/login";return}setItems(await r.json())}useEffect(()=>{load()},[]);
async function add(e:any){e.preventDefault();const r=await fetch("/api/admin/admins",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,name,password})});const d=await r.json();setMsg(d.error||"Đã thêm admin.");if(r.ok){setEmail("");setName("");setPassword("");load()}}
async function del(id:string){if(!confirm("Xóa admin này?"))return;const r=await fetch("/api/admin/admins",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const d=await r.json();if(!r.ok)setMsg(d.error);load()}
return <main className="page"><div className="container"><div className="kicker">Admin / Tài khoản</div><h1>Quản lý Admin</h1><form onSubmit={add} className="admin-box" style={{marginBottom:30}}><div style={{display:"grid",gap:12}}><input placeholder="Tên admin" value={name} onChange={e=>setName(e.target.value)} style={{padding:11,border:"1px solid #211f1a",background:"transparent"}}/><input placeholder="Email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} style={{padding:11,border:"1px solid #211f1a",background:"transparent"}}/><input placeholder="Mật khẩu tạm thời" type="password" required value={password} onChange={e=>setPassword(e.target.value)} style={{padding:11,border:"1px solid #211f1a",background:"transparent"}}/></div><button className="btn" style={{marginTop:15}}>Thêm Admin →</button>{msg&&<span className="mono" style={{marginLeft:12,fontSize:12}}>{msg}</span>}</form>
{items.map(a=><div className="admin-row" key={a.id}><span><strong>{a.name}</strong><br/><span className="mono" style={{fontSize:12}}>{a.email} · {a.role}</span></span>{a.role!=="owner"&&<button className="btn" onClick={()=>del(a.id)}>Xóa</button>}</div>)}</div></main>}
